//
// Autogenerated by Thrift Compiler (0.11.0)
//
// DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
//
"use strict";

var thrift = require('thrift');
var Thrift = thrift.Thrift;
var Q = thrift.Q;


var ttypes = require('./idl_search_plan_types');
//HELPER FUNCTIONS AND STRUCTURES

var SearchPlanService_doImageSearch_args = function(args) {
  this.request = null;
  if (args) {
    if (args.request !== undefined && args.request !== null) {
      this.request = new ttypes.SPRequest(args.request);
    }
  }
};
SearchPlanService_doImageSearch_args.prototype = {};
SearchPlanService_doImageSearch_args.prototype.read = function(input) {
  input.readStructBegin();
  while (true)
  {
    var ret = input.readFieldBegin();
    var fname = ret.fname;
    var ftype = ret.ftype;
    var fid = ret.fid;
    if (ftype == Thrift.Type.STOP) {
      break;
    }
    switch (fid)
    {
      case 1:
      if (ftype == Thrift.Type.STRUCT) {
        this.request = new ttypes.SPRequest();
        this.request.read(input);
      } else {
        input.skip(ftype);
      }
      break;
      case 0:
        input.skip(ftype);
        break;
      default:
        input.skip(ftype);
    }
    input.readFieldEnd();
  }
  input.readStructEnd();
  return;
};

SearchPlanService_doImageSearch_args.prototype.write = function(output) {
  output.writeStructBegin('SearchPlanService_doImageSearch_args');
  if (this.request !== null && this.request !== undefined) {
    output.writeFieldBegin('request', Thrift.Type.STRUCT, 1);
    this.request.write(output);
    output.writeFieldEnd();
  }
  output.writeFieldStop();
  output.writeStructEnd();
  return;
};

var SearchPlanService_doImageSearch_result = function(args) {
  this.success = null;
  this.qe = null;
  if (args instanceof ttypes.SPRequestException) {
    this.qe = args;
    return;
  }
  if (args) {
    if (args.success !== undefined && args.success !== null) {
      this.success = new ttypes.SPSearchResult(args.success);
    }
    if (args.qe !== undefined && args.qe !== null) {
      this.qe = args.qe;
    }
  }
};
SearchPlanService_doImageSearch_result.prototype = {};
SearchPlanService_doImageSearch_result.prototype.read = function(input) {
  input.readStructBegin();
  while (true)
  {
    var ret = input.readFieldBegin();
    var fname = ret.fname;
    var ftype = ret.ftype;
    var fid = ret.fid;
    if (ftype == Thrift.Type.STOP) {
      break;
    }
    switch (fid)
    {
      case 0:
      if (ftype == Thrift.Type.STRUCT) {
        this.success = new ttypes.SPSearchResult();
        this.success.read(input);
      } else {
        input.skip(ftype);
      }
      break;
      case 1:
      if (ftype == Thrift.Type.STRUCT) {
        this.qe = new ttypes.SPRequestException();
        this.qe.read(input);
      } else {
        input.skip(ftype);
      }
      break;
      default:
        input.skip(ftype);
    }
    input.readFieldEnd();
  }
  input.readStructEnd();
  return;
};

SearchPlanService_doImageSearch_result.prototype.write = function(output) {
  output.writeStructBegin('SearchPlanService_doImageSearch_result');
  if (this.success !== null && this.success !== undefined) {
    output.writeFieldBegin('success', Thrift.Type.STRUCT, 0);
    this.success.write(output);
    output.writeFieldEnd();
  }
  if (this.qe !== null && this.qe !== undefined) {
    output.writeFieldBegin('qe', Thrift.Type.STRUCT, 1);
    this.qe.write(output);
    output.writeFieldEnd();
  }
  output.writeFieldStop();
  output.writeStructEnd();
  return;
};

var SearchPlanServiceClient = exports.Client = function(output, pClass) {
    this.output = output;
    this.pClass = pClass;
    this._seqid = 0;
    this._reqs = {};
};
SearchPlanServiceClient.prototype = {};
SearchPlanServiceClient.prototype.seqid = function() { return this._seqid; };
SearchPlanServiceClient.prototype.new_seqid = function() { return this._seqid += 1; };
SearchPlanServiceClient.prototype.doImageSearch = function(request, callback) {
  this._seqid = this.new_seqid();
  if (callback === undefined) {
    var _defer = Q.defer();
    this._reqs[this.seqid()] = function(error, result) {
      if (error) {
        _defer.reject(error);
      } else {
        _defer.resolve(result);
      }
    };
    this.send_doImageSearch(request);
    return _defer.promise;
  } else {
    this._reqs[this.seqid()] = callback;
    this.send_doImageSearch(request);
  }
};

SearchPlanServiceClient.prototype.send_doImageSearch = function(request) {
  var output = new this.pClass(this.output);
  output.writeMessageBegin('doImageSearch', Thrift.MessageType.CALL, this.seqid());
  var params = {
    request: request
  };
  var args = new SearchPlanService_doImageSearch_args(params);
  args.write(output);
  output.writeMessageEnd();
  return this.output.flush();
};

SearchPlanServiceClient.prototype.recv_doImageSearch = function(input,mtype,rseqid) {
  var callback = this._reqs[rseqid] || function() {};
  delete this._reqs[rseqid];
  if (mtype == Thrift.MessageType.EXCEPTION) {
    var x = new Thrift.TApplicationException();
    x.read(input);
    input.readMessageEnd();
    return callback(x);
  }
  var result = new SearchPlanService_doImageSearch_result();
  result.read(input);
  input.readMessageEnd();

  if (null !== result.qe) {
    return callback(result.qe);
  }
  if (null !== result.success) {
    return callback(null, result.success);
  }
  return callback('doImageSearch failed: unknown result');
};
var SearchPlanServiceProcessor = exports.Processor = function(handler) {
  this._handler = handler;
}
;
SearchPlanServiceProcessor.prototype.process = function(input, output) {
  var r = input.readMessageBegin();
  if (this['process_' + r.fname]) {
    return this['process_' + r.fname].call(this, r.rseqid, input, output);
  } else {
    input.skip(Thrift.Type.STRUCT);
    input.readMessageEnd();
    var x = new Thrift.TApplicationException(Thrift.TApplicationExceptionType.UNKNOWN_METHOD, 'Unknown function ' + r.fname);
    output.writeMessageBegin(r.fname, Thrift.MessageType.EXCEPTION, r.rseqid);
    x.write(output);
    output.writeMessageEnd();
    output.flush();
  }
}
;
SearchPlanServiceProcessor.prototype.process_doImageSearch = function(seqid, input, output) {
  var args = new SearchPlanService_doImageSearch_args();
  args.read(input);
  input.readMessageEnd();
  if (this._handler.doImageSearch.length === 1) {
    Q.fcall(this._handler.doImageSearch.bind(this._handler), args.request)
      .then(function(result) {
        var result_obj = new SearchPlanService_doImageSearch_result({success: result});
        output.writeMessageBegin("doImageSearch", Thrift.MessageType.REPLY, seqid);
        result_obj.write(output);
        output.writeMessageEnd();
        output.flush();
      }, function (err) {
        var result;
        if (err instanceof ttypes.SPRequestException) {
          result = new SearchPlanService_doImageSearch_result(err);
          output.writeMessageBegin("doImageSearch", Thrift.MessageType.REPLY, seqid);
        } else {
          result = new Thrift.TApplicationException(Thrift.TApplicationExceptionType.UNKNOWN, err.message);
          output.writeMessageBegin("doImageSearch", Thrift.MessageType.EXCEPTION, seqid);
        }
        result.write(output);
        output.writeMessageEnd();
        output.flush();
      });
  } else {
    this._handler.doImageSearch(args.request, function (err, result) {
      var result_obj;
      if ((err === null || typeof err === 'undefined') || err instanceof ttypes.SPRequestException) {
        result_obj = new SearchPlanService_doImageSearch_result((err !== null || typeof err === 'undefined') ? err : {success: result});
        output.writeMessageBegin("doImageSearch", Thrift.MessageType.REPLY, seqid);
      } else {
        result_obj = new Thrift.TApplicationException(Thrift.TApplicationExceptionType.UNKNOWN, err.message);
        output.writeMessageBegin("doImageSearch", Thrift.MessageType.EXCEPTION, seqid);
      }
      result_obj.write(output);
      output.writeMessageEnd();
      output.flush();
    });
  }
};
