# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: rpc_searcher_plan.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='rpc_searcher_plan.proto',
  package='search_plan',
  syntax='proto3',
  serialized_pb=_b('\n\x17rpc_searcher_plan.proto\x12\x0bsearch_plan\"\xa9\x02\n\tSPRequest\x12\x32\n\x04type\x18\x01 \x01(\x0e\x32$.search_plan.SPRequest.SPRequestType\x12\x0f\n\x07\x63omp_id\x18\x02 \x01(\x05\x12\x10\n\x08\x63raft_id\x18\x03 \x01(\x05\x12\x0e\n\x06styles\x18\x04 \x03(\x05\x12\x10\n\x08img_urls\x18\x05 \x03(\t\x12;\n\x0bsrch_params\x18\x06 \x03(\x0b\x32&.search_plan.SPRequest.SrchParamsEntry\x1a\x31\n\x0fSrchParamsEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t:\x02\x38\x01\"3\n\rSPRequestType\x12\x10\n\x0cIMAGE_SEARCH\x10\x00\x12\x10\n\x0cSEARCH_DEBUG\x10\x01\"Q\n\x0cSPReturnInfo\x12\x14\n\x0csrch_img_cnt\x18\x01 \x01(\x05\x12\x17\n\x0fsrch_sample_cnt\x18\x02 \x01(\x05\x12\x12\n\ndebug_info\x18\x03 \x03(\t\"\x1d\n\tSPProduct\x12\x10\n\x08prod_ids\x18\x01 \x03(\t\"\xd5\x01\n\x0eSPSearchResult\x12>\n\nret_status\x18\x01 \x01(\x0e\x32*.search_plan.SPSearchResult.SPReturnStatus\x12+\n\x08ret_info\x18\x02 \x01(\x0b\x32\x19.search_plan.SPReturnInfo\x12(\n\x08ret_prod\x18\x03 \x03(\x0b\x32\x16.search_plan.SPProduct\",\n\x0eSPReturnStatus\x12\r\n\tSEARCH_OK\x10\x00\x12\x0b\n\x07\x45RROR_1\x10\x01\x32Y\n\x11SearchPlanService\x12\x44\n\rdoImageSearch\x12\x16.search_plan.SPRequest\x1a\x1b.search_plan.SPSearchResultb\x06proto3')
)



_SPREQUEST_SPREQUESTTYPE = _descriptor.EnumDescriptor(
  name='SPRequestType',
  full_name='search_plan.SPRequest.SPRequestType',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='IMAGE_SEARCH', index=0, number=0,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='SEARCH_DEBUG', index=1, number=1,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=287,
  serialized_end=338,
)
_sym_db.RegisterEnumDescriptor(_SPREQUEST_SPREQUESTTYPE)

_SPSEARCHRESULT_SPRETURNSTATUS = _descriptor.EnumDescriptor(
  name='SPReturnStatus',
  full_name='search_plan.SPSearchResult.SPReturnStatus',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='SEARCH_OK', index=0, number=0,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='ERROR_1', index=1, number=1,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=624,
  serialized_end=668,
)
_sym_db.RegisterEnumDescriptor(_SPSEARCHRESULT_SPRETURNSTATUS)


_SPREQUEST_SRCHPARAMSENTRY = _descriptor.Descriptor(
  name='SrchParamsEntry',
  full_name='search_plan.SPRequest.SrchParamsEntry',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='key', full_name='search_plan.SPRequest.SrchParamsEntry.key', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='value', full_name='search_plan.SPRequest.SrchParamsEntry.value', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=_descriptor._ParseOptions(descriptor_pb2.MessageOptions(), _b('8\001')),
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=236,
  serialized_end=285,
)

_SPREQUEST = _descriptor.Descriptor(
  name='SPRequest',
  full_name='search_plan.SPRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='type', full_name='search_plan.SPRequest.type', index=0,
      number=1, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='comp_id', full_name='search_plan.SPRequest.comp_id', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='craft_id', full_name='search_plan.SPRequest.craft_id', index=2,
      number=3, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='styles', full_name='search_plan.SPRequest.styles', index=3,
      number=4, type=5, cpp_type=1, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='img_urls', full_name='search_plan.SPRequest.img_urls', index=4,
      number=5, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='srch_params', full_name='search_plan.SPRequest.srch_params', index=5,
      number=6, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[_SPREQUEST_SRCHPARAMSENTRY, ],
  enum_types=[
    _SPREQUEST_SPREQUESTTYPE,
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=41,
  serialized_end=338,
)


_SPRETURNINFO = _descriptor.Descriptor(
  name='SPReturnInfo',
  full_name='search_plan.SPReturnInfo',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='srch_img_cnt', full_name='search_plan.SPReturnInfo.srch_img_cnt', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='srch_sample_cnt', full_name='search_plan.SPReturnInfo.srch_sample_cnt', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='debug_info', full_name='search_plan.SPReturnInfo.debug_info', index=2,
      number=3, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=340,
  serialized_end=421,
)


_SPPRODUCT = _descriptor.Descriptor(
  name='SPProduct',
  full_name='search_plan.SPProduct',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='prod_ids', full_name='search_plan.SPProduct.prod_ids', index=0,
      number=1, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=423,
  serialized_end=452,
)


_SPSEARCHRESULT = _descriptor.Descriptor(
  name='SPSearchResult',
  full_name='search_plan.SPSearchResult',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='ret_status', full_name='search_plan.SPSearchResult.ret_status', index=0,
      number=1, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='ret_info', full_name='search_plan.SPSearchResult.ret_info', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='ret_prod', full_name='search_plan.SPSearchResult.ret_prod', index=2,
      number=3, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _SPSEARCHRESULT_SPRETURNSTATUS,
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=455,
  serialized_end=668,
)

_SPREQUEST_SRCHPARAMSENTRY.containing_type = _SPREQUEST
_SPREQUEST.fields_by_name['type'].enum_type = _SPREQUEST_SPREQUESTTYPE
_SPREQUEST.fields_by_name['srch_params'].message_type = _SPREQUEST_SRCHPARAMSENTRY
_SPREQUEST_SPREQUESTTYPE.containing_type = _SPREQUEST
_SPSEARCHRESULT.fields_by_name['ret_status'].enum_type = _SPSEARCHRESULT_SPRETURNSTATUS
_SPSEARCHRESULT.fields_by_name['ret_info'].message_type = _SPRETURNINFO
_SPSEARCHRESULT.fields_by_name['ret_prod'].message_type = _SPPRODUCT
_SPSEARCHRESULT_SPRETURNSTATUS.containing_type = _SPSEARCHRESULT
DESCRIPTOR.message_types_by_name['SPRequest'] = _SPREQUEST
DESCRIPTOR.message_types_by_name['SPReturnInfo'] = _SPRETURNINFO
DESCRIPTOR.message_types_by_name['SPProduct'] = _SPPRODUCT
DESCRIPTOR.message_types_by_name['SPSearchResult'] = _SPSEARCHRESULT
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

SPRequest = _reflection.GeneratedProtocolMessageType('SPRequest', (_message.Message,), dict(

  SrchParamsEntry = _reflection.GeneratedProtocolMessageType('SrchParamsEntry', (_message.Message,), dict(
    DESCRIPTOR = _SPREQUEST_SRCHPARAMSENTRY,
    __module__ = 'rpc_searcher_plan_pb2'
    # @@protoc_insertion_point(class_scope:search_plan.SPRequest.SrchParamsEntry)
    ))
  ,
  DESCRIPTOR = _SPREQUEST,
  __module__ = 'rpc_searcher_plan_pb2'
  # @@protoc_insertion_point(class_scope:search_plan.SPRequest)
  ))
_sym_db.RegisterMessage(SPRequest)
_sym_db.RegisterMessage(SPRequest.SrchParamsEntry)

SPReturnInfo = _reflection.GeneratedProtocolMessageType('SPReturnInfo', (_message.Message,), dict(
  DESCRIPTOR = _SPRETURNINFO,
  __module__ = 'rpc_searcher_plan_pb2'
  # @@protoc_insertion_point(class_scope:search_plan.SPReturnInfo)
  ))
_sym_db.RegisterMessage(SPReturnInfo)

SPProduct = _reflection.GeneratedProtocolMessageType('SPProduct', (_message.Message,), dict(
  DESCRIPTOR = _SPPRODUCT,
  __module__ = 'rpc_searcher_plan_pb2'
  # @@protoc_insertion_point(class_scope:search_plan.SPProduct)
  ))
_sym_db.RegisterMessage(SPProduct)

SPSearchResult = _reflection.GeneratedProtocolMessageType('SPSearchResult', (_message.Message,), dict(
  DESCRIPTOR = _SPSEARCHRESULT,
  __module__ = 'rpc_searcher_plan_pb2'
  # @@protoc_insertion_point(class_scope:search_plan.SPSearchResult)
  ))
_sym_db.RegisterMessage(SPSearchResult)


_SPREQUEST_SRCHPARAMSENTRY.has_options = True
_SPREQUEST_SRCHPARAMSENTRY._options = _descriptor._ParseOptions(descriptor_pb2.MessageOptions(), _b('8\001'))

_SEARCHPLANSERVICE = _descriptor.ServiceDescriptor(
  name='SearchPlanService',
  full_name='search_plan.SearchPlanService',
  file=DESCRIPTOR,
  index=0,
  options=None,
  serialized_start=670,
  serialized_end=759,
  methods=[
  _descriptor.MethodDescriptor(
    name='doImageSearch',
    full_name='search_plan.SearchPlanService.doImageSearch',
    index=0,
    containing_service=None,
    input_type=_SPREQUEST,
    output_type=_SPSEARCHRESULT,
    options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_SEARCHPLANSERVICE)

DESCRIPTOR.services_by_name['SearchPlanService'] = _SEARCHPLANSERVICE

# @@protoc_insertion_point(module_scope)
