# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: rpc_image_searcher.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='rpc_image_searcher.proto',
  package='image_searcher',
  syntax='proto3',
  serialized_pb=_b('\n\x18rpc_image_searcher.proto\x12\x0eimage_searcher\")\n\rISQueryVector\x12\n\n\x02id\x18\x01 \x01(\x05\x12\x0c\n\x04\x65mbs\x18\x02 \x03(\x02\"\xe4\x02\n\tISRequest\x12\x35\n\x04type\x18\x01 \x01(\x0e\x32\'.image_searcher.ISRequest.ISRequestType\x12\x0f\n\x07\x63omp_id\x18\x02 \x01(\x05\x12\x10\n\x08\x63raft_id\x18\x03 \x01(\x05\x12\x0e\n\x06styles\x18\x04 \x03(\x05\x12\x34\n\rquery_vectors\x18\x05 \x03(\x0b\x32\x1d.image_searcher.ISQueryVector\x12\x0f\n\x07vec_dim\x18\x06 \x01(\x05\x12>\n\x0bsrch_params\x18\x07 \x03(\x0b\x32).image_searcher.ISRequest.SrchParamsEntry\x1a\x31\n\x0fSrchParamsEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t:\x02\x38\x01\"3\n\rISRequestType\x12\x10\n\x0cIMAGE_SEARCH\x10\x00\x12\x10\n\x0cSEARCH_DEBUG\x10\x01\"Q\n\x0cISReturnInfo\x12\x14\n\x0csrch_img_cnt\x18\x01 \x01(\x05\x12\x17\n\x0fsrch_sample_cnt\x18\x02 \x01(\x05\x12\x12\n\ndebug_info\x18\x03 \x03(\t\"\x1d\n\tISProduct\x12\x10\n\x08prod_ids\x18\x01 \x03(\t\"\xfe\x01\n\x0eISSearchResult\x12\x41\n\nret_status\x18\x01 \x01(\x0e\x32-.image_searcher.ISSearchResult.ISReturnStatus\x12.\n\x08ret_info\x18\x02 \x01(\x0b\x32\x1c.image_searcher.ISReturnInfo\x12+\n\x08ret_prod\x18\x03 \x03(\x0b\x32\x19.image_searcher.ISProduct\"L\n\x0eISReturnStatus\x12\r\n\tSEARCH_OK\x10\x00\x12\x14\n\x10\x45RROR_NO_COMP_ID\x10\x01\x12\x15\n\x11\x45RROR_NO_CRAFT_ID\x10\x02\x32]\n\x14ImageSearcherService\x12\x45\n\x08\x64oSearch\x12\x19.image_searcher.ISRequest\x1a\x1e.image_searcher.ISSearchResultb\x06proto3')
)



_ISREQUEST_ISREQUESTTYPE = _descriptor.EnumDescriptor(
  name='ISRequestType',
  full_name='image_searcher.ISRequest.ISRequestType',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='IMAGE_SEARCH', index=0, number=0,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='SEARCH_DEBUG', index=1, number=1,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=393,
  serialized_end=444,
)
_sym_db.RegisterEnumDescriptor(_ISREQUEST_ISREQUESTTYPE)

_ISSEARCHRESULT_ISRETURNSTATUS = _descriptor.EnumDescriptor(
  name='ISReturnStatus',
  full_name='image_searcher.ISSearchResult.ISReturnStatus',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='SEARCH_OK', index=0, number=0,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='ERROR_NO_COMP_ID', index=1, number=1,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='ERROR_NO_CRAFT_ID', index=2, number=2,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=739,
  serialized_end=815,
)
_sym_db.RegisterEnumDescriptor(_ISSEARCHRESULT_ISRETURNSTATUS)


_ISQUERYVECTOR = _descriptor.Descriptor(
  name='ISQueryVector',
  full_name='image_searcher.ISQueryVector',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='image_searcher.ISQueryVector.id', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='embs', full_name='image_searcher.ISQueryVector.embs', index=1,
      number=2, type=2, cpp_type=6, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=44,
  serialized_end=85,
)


_ISREQUEST_SRCHPARAMSENTRY = _descriptor.Descriptor(
  name='SrchParamsEntry',
  full_name='image_searcher.ISRequest.SrchParamsEntry',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='key', full_name='image_searcher.ISRequest.SrchParamsEntry.key', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='value', full_name='image_searcher.ISRequest.SrchParamsEntry.value', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=_descriptor._ParseOptions(descriptor_pb2.MessageOptions(), _b('8\001')),
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=342,
  serialized_end=391,
)

_ISREQUEST = _descriptor.Descriptor(
  name='ISRequest',
  full_name='image_searcher.ISRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='type', full_name='image_searcher.ISRequest.type', index=0,
      number=1, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='comp_id', full_name='image_searcher.ISRequest.comp_id', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='craft_id', full_name='image_searcher.ISRequest.craft_id', index=2,
      number=3, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='styles', full_name='image_searcher.ISRequest.styles', index=3,
      number=4, type=5, cpp_type=1, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='query_vectors', full_name='image_searcher.ISRequest.query_vectors', index=4,
      number=5, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='vec_dim', full_name='image_searcher.ISRequest.vec_dim', index=5,
      number=6, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='srch_params', full_name='image_searcher.ISRequest.srch_params', index=6,
      number=7, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[_ISREQUEST_SRCHPARAMSENTRY, ],
  enum_types=[
    _ISREQUEST_ISREQUESTTYPE,
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=88,
  serialized_end=444,
)


_ISRETURNINFO = _descriptor.Descriptor(
  name='ISReturnInfo',
  full_name='image_searcher.ISReturnInfo',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='srch_img_cnt', full_name='image_searcher.ISReturnInfo.srch_img_cnt', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='srch_sample_cnt', full_name='image_searcher.ISReturnInfo.srch_sample_cnt', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='debug_info', full_name='image_searcher.ISReturnInfo.debug_info', index=2,
      number=3, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=446,
  serialized_end=527,
)


_ISPRODUCT = _descriptor.Descriptor(
  name='ISProduct',
  full_name='image_searcher.ISProduct',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='prod_ids', full_name='image_searcher.ISProduct.prod_ids', index=0,
      number=1, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=529,
  serialized_end=558,
)


_ISSEARCHRESULT = _descriptor.Descriptor(
  name='ISSearchResult',
  full_name='image_searcher.ISSearchResult',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='ret_status', full_name='image_searcher.ISSearchResult.ret_status', index=0,
      number=1, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='ret_info', full_name='image_searcher.ISSearchResult.ret_info', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='ret_prod', full_name='image_searcher.ISSearchResult.ret_prod', index=2,
      number=3, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _ISSEARCHRESULT_ISRETURNSTATUS,
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=561,
  serialized_end=815,
)

_ISREQUEST_SRCHPARAMSENTRY.containing_type = _ISREQUEST
_ISREQUEST.fields_by_name['type'].enum_type = _ISREQUEST_ISREQUESTTYPE
_ISREQUEST.fields_by_name['query_vectors'].message_type = _ISQUERYVECTOR
_ISREQUEST.fields_by_name['srch_params'].message_type = _ISREQUEST_SRCHPARAMSENTRY
_ISREQUEST_ISREQUESTTYPE.containing_type = _ISREQUEST
_ISSEARCHRESULT.fields_by_name['ret_status'].enum_type = _ISSEARCHRESULT_ISRETURNSTATUS
_ISSEARCHRESULT.fields_by_name['ret_info'].message_type = _ISRETURNINFO
_ISSEARCHRESULT.fields_by_name['ret_prod'].message_type = _ISPRODUCT
_ISSEARCHRESULT_ISRETURNSTATUS.containing_type = _ISSEARCHRESULT
DESCRIPTOR.message_types_by_name['ISQueryVector'] = _ISQUERYVECTOR
DESCRIPTOR.message_types_by_name['ISRequest'] = _ISREQUEST
DESCRIPTOR.message_types_by_name['ISReturnInfo'] = _ISRETURNINFO
DESCRIPTOR.message_types_by_name['ISProduct'] = _ISPRODUCT
DESCRIPTOR.message_types_by_name['ISSearchResult'] = _ISSEARCHRESULT
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

ISQueryVector = _reflection.GeneratedProtocolMessageType('ISQueryVector', (_message.Message,), dict(
  DESCRIPTOR = _ISQUERYVECTOR,
  __module__ = 'rpc_image_searcher_pb2'
  # @@protoc_insertion_point(class_scope:image_searcher.ISQueryVector)
  ))
_sym_db.RegisterMessage(ISQueryVector)

ISRequest = _reflection.GeneratedProtocolMessageType('ISRequest', (_message.Message,), dict(

  SrchParamsEntry = _reflection.GeneratedProtocolMessageType('SrchParamsEntry', (_message.Message,), dict(
    DESCRIPTOR = _ISREQUEST_SRCHPARAMSENTRY,
    __module__ = 'rpc_image_searcher_pb2'
    # @@protoc_insertion_point(class_scope:image_searcher.ISRequest.SrchParamsEntry)
    ))
  ,
  DESCRIPTOR = _ISREQUEST,
  __module__ = 'rpc_image_searcher_pb2'
  # @@protoc_insertion_point(class_scope:image_searcher.ISRequest)
  ))
_sym_db.RegisterMessage(ISRequest)
_sym_db.RegisterMessage(ISRequest.SrchParamsEntry)

ISReturnInfo = _reflection.GeneratedProtocolMessageType('ISReturnInfo', (_message.Message,), dict(
  DESCRIPTOR = _ISRETURNINFO,
  __module__ = 'rpc_image_searcher_pb2'
  # @@protoc_insertion_point(class_scope:image_searcher.ISReturnInfo)
  ))
_sym_db.RegisterMessage(ISReturnInfo)

ISProduct = _reflection.GeneratedProtocolMessageType('ISProduct', (_message.Message,), dict(
  DESCRIPTOR = _ISPRODUCT,
  __module__ = 'rpc_image_searcher_pb2'
  # @@protoc_insertion_point(class_scope:image_searcher.ISProduct)
  ))
_sym_db.RegisterMessage(ISProduct)

ISSearchResult = _reflection.GeneratedProtocolMessageType('ISSearchResult', (_message.Message,), dict(
  DESCRIPTOR = _ISSEARCHRESULT,
  __module__ = 'rpc_image_searcher_pb2'
  # @@protoc_insertion_point(class_scope:image_searcher.ISSearchResult)
  ))
_sym_db.RegisterMessage(ISSearchResult)


_ISREQUEST_SRCHPARAMSENTRY.has_options = True
_ISREQUEST_SRCHPARAMSENTRY._options = _descriptor._ParseOptions(descriptor_pb2.MessageOptions(), _b('8\001'))

_IMAGESEARCHERSERVICE = _descriptor.ServiceDescriptor(
  name='ImageSearcherService',
  full_name='image_searcher.ImageSearcherService',
  file=DESCRIPTOR,
  index=0,
  options=None,
  serialized_start=817,
  serialized_end=910,
  methods=[
  _descriptor.MethodDescriptor(
    name='doSearch',
    full_name='image_searcher.ImageSearcherService.doSearch',
    index=0,
    containing_service=None,
    input_type=_ISREQUEST,
    output_type=_ISSEARCHRESULT,
    options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_IMAGESEARCHERSERVICE)

DESCRIPTOR.services_by_name['ImageSearcherService'] = _IMAGESEARCHERSERVICE

# @@protoc_insertion_point(module_scope)
