/**
 * Autogenerated by Thrift Compiler (0.11.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
@SuppressWarnings({"cast", "rawtypes", "serial", "unchecked", "unused"})
@javax.annotation.Generated(value = "Autogenerated by Thrift Compiler (0.11.0)", date = "2018-08-03")
public class SPReturnProduct implements org.apache.thrift.TBase<SPReturnProduct, SPReturnProduct._Fields>, java.io.Serializable, Cloneable, Comparable<SPReturnProduct> {
  private static final org.apache.thrift.protocol.TStruct STRUCT_DESC = new org.apache.thrift.protocol.TStruct("SPReturnProduct");

  private static final org.apache.thrift.protocol.TField LIST_PRODS_FIELD_DESC = new org.apache.thrift.protocol.TField("list_prods", org.apache.thrift.protocol.TType.LIST, (short)1);

  private static final org.apache.thrift.scheme.SchemeFactory STANDARD_SCHEME_FACTORY = new SPReturnProductStandardSchemeFactory();
  private static final org.apache.thrift.scheme.SchemeFactory TUPLE_SCHEME_FACTORY = new SPReturnProductTupleSchemeFactory();

  public java.util.List<java.lang.Integer> list_prods; // required

  /** The set of fields this struct contains, along with convenience methods for finding and manipulating them. */
  public enum _Fields implements org.apache.thrift.TFieldIdEnum {
    LIST_PRODS((short)1, "list_prods");

    private static final java.util.Map<java.lang.String, _Fields> byName = new java.util.HashMap<java.lang.String, _Fields>();

    static {
      for (_Fields field : java.util.EnumSet.allOf(_Fields.class)) {
        byName.put(field.getFieldName(), field);
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, or null if its not found.
     */
    public static _Fields findByThriftId(int fieldId) {
      switch(fieldId) {
        case 1: // LIST_PRODS
          return LIST_PRODS;
        default:
          return null;
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, throwing an exception
     * if it is not found.
     */
    public static _Fields findByThriftIdOrThrow(int fieldId) {
      _Fields fields = findByThriftId(fieldId);
      if (fields == null) throw new java.lang.IllegalArgumentException("Field " + fieldId + " doesn't exist!");
      return fields;
    }

    /**
     * Find the _Fields constant that matches name, or null if its not found.
     */
    public static _Fields findByName(java.lang.String name) {
      return byName.get(name);
    }

    private final short _thriftId;
    private final java.lang.String _fieldName;

    _Fields(short thriftId, java.lang.String fieldName) {
      _thriftId = thriftId;
      _fieldName = fieldName;
    }

    public short getThriftFieldId() {
      return _thriftId;
    }

    public java.lang.String getFieldName() {
      return _fieldName;
    }
  }

  // isset id assignments
  public static final java.util.Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> metaDataMap;
  static {
    java.util.Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> tmpMap = new java.util.EnumMap<_Fields, org.apache.thrift.meta_data.FieldMetaData>(_Fields.class);
    tmpMap.put(_Fields.LIST_PRODS, new org.apache.thrift.meta_data.FieldMetaData("list_prods", org.apache.thrift.TFieldRequirementType.REQUIRED, 
        new org.apache.thrift.meta_data.ListMetaData(org.apache.thrift.protocol.TType.LIST, 
            new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.I32))));
    metaDataMap = java.util.Collections.unmodifiableMap(tmpMap);
    org.apache.thrift.meta_data.FieldMetaData.addStructMetaDataMap(SPReturnProduct.class, metaDataMap);
  }

  public SPReturnProduct() {
  }

  public SPReturnProduct(
    java.util.List<java.lang.Integer> list_prods)
  {
    this();
    this.list_prods = list_prods;
  }

  /**
   * Performs a deep copy on <i>other</i>.
   */
  public SPReturnProduct(SPReturnProduct other) {
    if (other.isSetList_prods()) {
      java.util.List<java.lang.Integer> __this__list_prods = new java.util.ArrayList<java.lang.Integer>(other.list_prods);
      this.list_prods = __this__list_prods;
    }
  }

  public SPReturnProduct deepCopy() {
    return new SPReturnProduct(this);
  }

  @Override
  public void clear() {
    this.list_prods = null;
  }

  public int getList_prodsSize() {
    return (this.list_prods == null) ? 0 : this.list_prods.size();
  }

  public java.util.Iterator<java.lang.Integer> getList_prodsIterator() {
    return (this.list_prods == null) ? null : this.list_prods.iterator();
  }

  public void addToList_prods(int elem) {
    if (this.list_prods == null) {
      this.list_prods = new java.util.ArrayList<java.lang.Integer>();
    }
    this.list_prods.add(elem);
  }

  public java.util.List<java.lang.Integer> getList_prods() {
    return this.list_prods;
  }

  public SPReturnProduct setList_prods(java.util.List<java.lang.Integer> list_prods) {
    this.list_prods = list_prods;
    return this;
  }

  public void unsetList_prods() {
    this.list_prods = null;
  }

  /** Returns true if field list_prods is set (has been assigned a value) and false otherwise */
  public boolean isSetList_prods() {
    return this.list_prods != null;
  }

  public void setList_prodsIsSet(boolean value) {
    if (!value) {
      this.list_prods = null;
    }
  }

  public void setFieldValue(_Fields field, java.lang.Object value) {
    switch (field) {
    case LIST_PRODS:
      if (value == null) {
        unsetList_prods();
      } else {
        setList_prods((java.util.List<java.lang.Integer>)value);
      }
      break;

    }
  }

  public java.lang.Object getFieldValue(_Fields field) {
    switch (field) {
    case LIST_PRODS:
      return getList_prods();

    }
    throw new java.lang.IllegalStateException();
  }

  /** Returns true if field corresponding to fieldID is set (has been assigned a value) and false otherwise */
  public boolean isSet(_Fields field) {
    if (field == null) {
      throw new java.lang.IllegalArgumentException();
    }

    switch (field) {
    case LIST_PRODS:
      return isSetList_prods();
    }
    throw new java.lang.IllegalStateException();
  }

  @Override
  public boolean equals(java.lang.Object that) {
    if (that == null)
      return false;
    if (that instanceof SPReturnProduct)
      return this.equals((SPReturnProduct)that);
    return false;
  }

  public boolean equals(SPReturnProduct that) {
    if (that == null)
      return false;
    if (this == that)
      return true;

    boolean this_present_list_prods = true && this.isSetList_prods();
    boolean that_present_list_prods = true && that.isSetList_prods();
    if (this_present_list_prods || that_present_list_prods) {
      if (!(this_present_list_prods && that_present_list_prods))
        return false;
      if (!this.list_prods.equals(that.list_prods))
        return false;
    }

    return true;
  }

  @Override
  public int hashCode() {
    int hashCode = 1;

    hashCode = hashCode * 8191 + ((isSetList_prods()) ? 131071 : 524287);
    if (isSetList_prods())
      hashCode = hashCode * 8191 + list_prods.hashCode();

    return hashCode;
  }

  @Override
  public int compareTo(SPReturnProduct other) {
    if (!getClass().equals(other.getClass())) {
      return getClass().getName().compareTo(other.getClass().getName());
    }

    int lastComparison = 0;

    lastComparison = java.lang.Boolean.valueOf(isSetList_prods()).compareTo(other.isSetList_prods());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetList_prods()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.list_prods, other.list_prods);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    return 0;
  }

  public _Fields fieldForId(int fieldId) {
    return _Fields.findByThriftId(fieldId);
  }

  public void read(org.apache.thrift.protocol.TProtocol iprot) throws org.apache.thrift.TException {
    scheme(iprot).read(iprot, this);
  }

  public void write(org.apache.thrift.protocol.TProtocol oprot) throws org.apache.thrift.TException {
    scheme(oprot).write(oprot, this);
  }

  @Override
  public java.lang.String toString() {
    java.lang.StringBuilder sb = new java.lang.StringBuilder("SPReturnProduct(");
    boolean first = true;

    sb.append("list_prods:");
    if (this.list_prods == null) {
      sb.append("null");
    } else {
      sb.append(this.list_prods);
    }
    first = false;
    sb.append(")");
    return sb.toString();
  }

  public void validate() throws org.apache.thrift.TException {
    // check for required fields
    if (list_prods == null) {
      throw new org.apache.thrift.protocol.TProtocolException("Required field 'list_prods' was not present! Struct: " + toString());
    }
    // check for sub-struct validity
  }

  private void writeObject(java.io.ObjectOutputStream out) throws java.io.IOException {
    try {
      write(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(out)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }

  private void readObject(java.io.ObjectInputStream in) throws java.io.IOException, java.lang.ClassNotFoundException {
    try {
      read(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(in)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }

  private static class SPReturnProductStandardSchemeFactory implements org.apache.thrift.scheme.SchemeFactory {
    public SPReturnProductStandardScheme getScheme() {
      return new SPReturnProductStandardScheme();
    }
  }

  private static class SPReturnProductStandardScheme extends org.apache.thrift.scheme.StandardScheme<SPReturnProduct> {

    public void read(org.apache.thrift.protocol.TProtocol iprot, SPReturnProduct struct) throws org.apache.thrift.TException {
      org.apache.thrift.protocol.TField schemeField;
      iprot.readStructBegin();
      while (true)
      {
        schemeField = iprot.readFieldBegin();
        if (schemeField.type == org.apache.thrift.protocol.TType.STOP) { 
          break;
        }
        switch (schemeField.id) {
          case 1: // LIST_PRODS
            if (schemeField.type == org.apache.thrift.protocol.TType.LIST) {
              {
                org.apache.thrift.protocol.TList _list34 = iprot.readListBegin();
                struct.list_prods = new java.util.ArrayList<java.lang.Integer>(_list34.size);
                int _elem35;
                for (int _i36 = 0; _i36 < _list34.size; ++_i36)
                {
                  _elem35 = iprot.readI32();
                  struct.list_prods.add(_elem35);
                }
                iprot.readListEnd();
              }
              struct.setList_prodsIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          default:
            org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
        }
        iprot.readFieldEnd();
      }
      iprot.readStructEnd();

      // check for required fields of primitive type, which can't be checked in the validate method
      struct.validate();
    }

    public void write(org.apache.thrift.protocol.TProtocol oprot, SPReturnProduct struct) throws org.apache.thrift.TException {
      struct.validate();

      oprot.writeStructBegin(STRUCT_DESC);
      if (struct.list_prods != null) {
        oprot.writeFieldBegin(LIST_PRODS_FIELD_DESC);
        {
          oprot.writeListBegin(new org.apache.thrift.protocol.TList(org.apache.thrift.protocol.TType.I32, struct.list_prods.size()));
          for (int _iter37 : struct.list_prods)
          {
            oprot.writeI32(_iter37);
          }
          oprot.writeListEnd();
        }
        oprot.writeFieldEnd();
      }
      oprot.writeFieldStop();
      oprot.writeStructEnd();
    }

  }

  private static class SPReturnProductTupleSchemeFactory implements org.apache.thrift.scheme.SchemeFactory {
    public SPReturnProductTupleScheme getScheme() {
      return new SPReturnProductTupleScheme();
    }
  }

  private static class SPReturnProductTupleScheme extends org.apache.thrift.scheme.TupleScheme<SPReturnProduct> {

    @Override
    public void write(org.apache.thrift.protocol.TProtocol prot, SPReturnProduct struct) throws org.apache.thrift.TException {
      org.apache.thrift.protocol.TTupleProtocol oprot = (org.apache.thrift.protocol.TTupleProtocol) prot;
      {
        oprot.writeI32(struct.list_prods.size());
        for (int _iter38 : struct.list_prods)
        {
          oprot.writeI32(_iter38);
        }
      }
    }

    @Override
    public void read(org.apache.thrift.protocol.TProtocol prot, SPReturnProduct struct) throws org.apache.thrift.TException {
      org.apache.thrift.protocol.TTupleProtocol iprot = (org.apache.thrift.protocol.TTupleProtocol) prot;
      {
        org.apache.thrift.protocol.TList _list39 = new org.apache.thrift.protocol.TList(org.apache.thrift.protocol.TType.I32, iprot.readI32());
        struct.list_prods = new java.util.ArrayList<java.lang.Integer>(_list39.size);
        int _elem40;
        for (int _i41 = 0; _i41 < _list39.size; ++_i41)
        {
          _elem40 = iprot.readI32();
          struct.list_prods.add(_elem40);
        }
      }
      struct.setList_prodsIsSet(true);
    }
  }

  private static <S extends org.apache.thrift.scheme.IScheme> S scheme(org.apache.thrift.protocol.TProtocol proto) {
    return (org.apache.thrift.scheme.StandardScheme.class.equals(proto.getScheme()) ? STANDARD_SCHEME_FACTORY : TUPLE_SCHEME_FACTORY).getScheme();
  }
}

