/**
 * Autogenerated by Thrift Compiler (0.11.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */

public enum SPReturnStatus implements org.apache.thrift.TEnum {
  SEARCH_OK(0),
  ERROR_1(1);

  private final int value;

  private SPReturnStatus(int value) {
    this.value = value;
  }

  /**
   * Get the integer value of this enum value, as defined in the Thrift IDL.
   */
  public int getValue() {
    return value;
  }

  /**
   * Find a the enum type by its integer value, as defined in the Thrift IDL.
   * @return null if the value is not found.
   */
  public static SPReturnStatus findByValue(int value) { 
    switch (value) {
      case 0:
        return SEARCH_OK;
      case 1:
        return ERROR_1;
      default:
        return null;
    }
  }
}
